### ISSUE TITLE
add admonition type: question

### ISSUE THREAD

**Issue by arcturus140** [nebrelbug/react-admonitions#2]
I think it would be super useful if a new admonition type would be added: `question` to highlight a quesiton.

**Comment by bgub** [comment]
@arcturus140 that's a great idea! Would you like to submit a pull request?

**Comment by arcturus140** [comment]
@nebrelbug,

didn't have that in mind. I never worked with react or js but it should be trivial to add the question type to the existing ones. How can I view it on localhost for development?

I tried `npm install --save react-admonitions` and `npm run`

**Comment by bgub** [comment]
After Git cloning, `cd` into the folder and run `npm install`.

Then, `cd example` and run `npm start`

**Comment by bgub** [comment]
It should be fairly easy to add the change. React-Admonitions uses SVG codes from [Octicons](https://octicons.github.com/) so you'd pick an icon from there.

Good luck! :smiley:
