### ISSUE TITLE
Readable text on nested admonitions?

### ISSUE THREAD

**Issue by arcturus140** [nebrelbug/react-admonitions#4]
Admonitions can be nested:

![image](https://user-images.githubusercontent.com/44707562/67769511-82c64080-fa4c-11e9-9bf1-0edfd425adbf.png)

title h5 and background are of the same colour, background with alpha channel:

```
.admonition-important {
  background-color: rgba(52, 152, 219, 0.1);
}

.admonition-important h5 {
  color: #3498db;
}
```

Nested admonitions are increasingly more difficult to read with lower contrast between text and background due to alpha channel. 

I am not sure if this is even an issue, because

1. Even on 10th level it is readable well on white background
2. Becomes very hard to read only at 40th+ level on white background
3. I still haven't figured out the behaviour, was trying to calculate the level where text colour == background colour

![image](https://user-images.githubusercontent.com/44707562/67770747-e3ef1380-fa4e-11e9-8de5-35b10173ae5e.png)

**Comment by bgub** [comment]
@arcturus140 thanks for the detailed testing and info! I'm inclined to think this will be okay for most people.

I suppose we could provide an option for users to set opacity.

**Comment by arcturus140** [comment]
yes, this thought came up and I started testing. Turner turned out to be much less a deal than expected. 

it was worth mentioning but I'll close this for now.

**Comment by bgub** [comment]
@arcturus140 alright. Thanks!
