### ISSUE TITLE
docusaurus v2 admonitions

### ISSUE THREAD

**Issue by prasathsekar** [nebrelbug/react-admonitions#5]
I have tried to use react-admonitions in docusaurus v2.

I have done 

npm install --save react-admonitions

Then used the below code in my markdown file it showing error

Code:

```jsx
import React, { Component } from 'react'

import Admonition from 'react-admonitions'

class Example extends Component {
  render() {
    return (
      <Admonition type="warning" title="Do not do this">
        Admonition Content
      </Admonition>
    )
  }
}
```
This is what i have done.

**Comment by bgub** [comment]
Would you mind posting what the error message says? Also, try renaming your `.md` file to `.mdx`

P.S. I edited your issue to improve reading

**Comment by prasathsekar** [comment]
This the following error 

SyntaxError: /home/prasath/Desktop/prasath_doc/docs/test.mdx: Identifier 'React' has already been declared (11:7)

   9 | };
  10 |   /* @jsx mdx */
> 11 | import React, { Component } from 'react'
     |        ^
  12 | import Admonition from 'react-admonitions'
  13 | export const rightToc = [{
  14 |   value: 'Install and use',
 @ ./.docusaurus/registry.js 702:15-58 697:13-699:29
 @ ./node_modules/@docusaurus/core/lib/client/exports/ComponentCreator.js
 @ ./.docusaurus/routes.js
 @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
 @ multi (webpack)-dev-server/client?http://localhost (webpack)/hot/dev-server.js ./node_modules/@docusaurus/core/lib/client/clientEntry.js

**Comment by bgub** [comment]
Hi @prasathsekar, React is actually imported by default, and I don't think MDX supports writing class-based components.

This should work:

```mdx
import Admonition from 'react-admonitions'

<Admonition type="warning" title="Do not do this">
Admonition Content
</Admonition>
```

**Comment by prasathsekar** [comment]
Yes Done. Now it is working perfect.
